version: '3'
services:
  bingo:
    image: 2d281a4e0941
    container_name: bingo
    networks:
      bingo_network:
        ipv4_address: 172.18.0.2  # Замените этот адрес на желаемый
    volumes:
      - /opt/bongo/logs/fcdc2958fa
    healthcheck:
      test: curl http://172.18.0.2:22549/ping
      interval: 30s
    restart: always

  bingo_replica:
    image: 2d281a4e0941
    container_name: bingo_replica
    networks:
      bingo_network:
        ipv4_address: 172.18.0.3  # Замените этот адрес на желаемый
    volumes:
      - /opt/bongo/logs/replica
    healthcheck:
      test: curl http://172.18.0.3:22549/ping
      interval: 30s
    restart: always

  load_balancer:
    image: nginx
    container_name: load_balancer
    ports:
      - "127.0.0.1:22549:80"
    networks:
      - bingo_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bingo
      - bingo_replica
    restart: always

networks:
  bingo_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
